---
deployment:
  tasks:
    - export DEPLOYPATH=/home/zlandjvw/public_html/
    - /bin/cp index.html $DEPLOYPATH
    - /bin/cp index-terms.html $DEPLOYPATH
    - /bin/cp index-sign-up.html $DEPLOYPATH
    - /bin/cp index-contact-us.html $DEPLOYPATH
    - /bin/cp index-about-us.html $DEPLOYPATH
    - /bin/cp -R js $DEPLOYPATH
    - /bin/cp -R css $DEPLOYPATH
    - /bin/cp -R assets $DEPLOYPATH
